# Generated by Django 5.0.12 on 2025-03-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
            preserve_default=False,
        ),
    ]
